name: Tests

on:
  # Runt test on main branch
  push:
    branches: [ "main" ]

  # Run tests for any PRs.
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag image-resizer-app

  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: image-resizer-app
    steps:
      - run: cd /workspace/image-resizer-app/build/
      - name: Run tests
        run: ctest --output-on-failure option
