name: Tests

on:
  # Runt test on main branch
  push:
    branches: [ "main" ]

  # Run tests for any PRs.
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build image
      run: docker build . --file Dockerfile --tag image-resizer-app
    - name: Run tests
      run: |
        docker run -e CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }} image-resizer-app \
          /bin/bash -c "sh /workspace/image-resizer-app/tests/run_tests.sh"

